#CATEGORIA_SITIO = [
#    dict(label="AEROPUERTO", value="Categoria de sitio_AEROPUERTO"),
#    dict(label="AREA RURAL", value="Categoria de sitio_AREA RURAL"),
#    dict(label="CENTRO EDUCATIVO", value="Categoria de sitio_CENTRO EDUCATIVO"),
#    dict(label="CENTRO RELIGIOSO", value="Categoria de sitio_CENTRO RELIGIOSO"),
#    dict(label="CENTRO SOCIAL/CULTURAL", value="Categoria de sitio_CENTRO SOCIAL/CULTURAL"),
#    dict(label="CENTRO TURISTICO/RECREACIONAL", value="Categoria de sitio_CENTRO TURISTICO/RECREACIONAL"),
#    dict(label="CONSTRUCCION", value="Categoria de sitio_CONSTRUCCION"),
#    dict(label="ENTIDAD PUBLICA", value="Categoria de sitio_ENTIDAD PUBLICA"),
#    dict(label="ESTACION TRANSPORTE PUBLICO", value="Categoria de sitio_ESTACION TRANSPORTE PUBLICO"),
#    dict(label="FUERZA PUBLICA", value="Categoria de sitio_FUERZA PUBLICA"),
#    dict(label="INSTITUTOS DE SALUD", value="Categoria de sitio_INSTITUTOS DE SALUD"),
#    dict(label="LOCAL ALIMENTOS", value="Categoria de sitio_LOCAL ALIMENTOS"),
#    dict(label="LOCAL COMERCIAL", value="Categoria de sitio_LOCAL COMERCIAL"),
#    dict(label="LOCAL FINANCIERO", value="Categoria de sitio_LOCAL FINANCIERO"),
#    dict(label="LOCAL SERVICIO AUTOMOTRIZ", value="Categoria de sitio_LOCAL SERVICIO AUTOMOTRIZ"),
#    dict(label="LOCAL SERVICIO ENTRETENIMIENTO", value="Categoria de sitio_LOCAL SERVICIO ENTRETENIMIENTO"),
#    dict(label="LOCAL SERVICIO HOSPEDAJE", value="Categoria de sitio_LOCAL SERVICIO HOSPEDAJE"),
#    dict(label="LOTE BALDIO", value="LOTE BALDIO"),
#    dict(label="OTRO", value="Categoria de sitio_OTRO"),
#    dict(label="SECTOR INDUSTRIA", value="Categoria de sitio_SECTOR INDUSTRIA"),
#    dict(label="SECTOR MARITIMO Y FLUVIAL", value="Categoria de sitio_SECTOR MARITIMO Y FLUVIAL"),
#    dict(label="SERVICIO FUNERARIO", value="Categoria de sitio_SERVICIO FUNERARIO"),
#    dict(label="VIAS PUBLICAS", value="Categoria de sitio_VIAS PUBLICAS"),
#    dict(label="VIVIENDAS", value="Categoria de sitio_VIVIENDAS"),
#]

#ARMA_EMPLEADA = [
#    dict(label="ARMA BLANCA / CORTOPUNZANTE", value="Arma empleada_ARMA BLANCA / CORTOPUNZANTE"),
#    dict(label="ARMA DE FUEGO", value="Arma empleada_ARMA DE FUEGO"),
#    dict(label="CONTUNDENTES", value="Arma empleada_CONTUNDENTES"),
#    dict(label="ESCOPOLAMINA", value="Arma empleada_ESCOPOLAMINA"),
#    dict(label="NO REPORTADO", value="Arma empleada_NO REPORTADO"),
#    dict(label="SIN EMPLEO DE ARMAS", value="Arma empleada_SIN EMPLEO DE ARMAS"),
#]

PREDICT_COLUMNS = {
    #"Categoria de sitio_AEROPUERTO":0,
    #"Categoria de sitio_AREA RURAL":0,
    #"Categoria de sitio_CENTRO EDUCATIVO":0,
    #"Categoria de sitio_CENTRO RELIGIOSO":0,
    #"Categoria de sitio_CENTRO SOCIAL/CULTURAL":0,
    #"Categoria de sitio_CENTRO TURISTICO/RECREACIONAL":0,
    #"Categoria de sitio_CONSTRUCCION":0,
    #"Categoria de sitio_ENTIDAD PUBLICA":0,
    #"Categoria de sitio_ESTACION TRANSPORTE PUBLICO":0,
    #"Categoria de sitio_FUERZA PUBLICA":0,
    #"Categoria de sitio_INSTITUTOS DE SALUD":0,
    #"Categoria de sitio_LOCAL ALIMENTOS":0,
    #"Categoria de sitio_LOCAL COMERCIAL":0,
    #"Categoria de sitio_LOCAL FINANCIERO":0,
    #"Categoria de sitio_LOCAL SERVICIO AUTOMOTRIZ":0,
    #"Categoria de sitio_LOCAL SERVICIO ENTRETENIMIENTO":0,
    #"Categoria de sitio_LOCAL SERVICIO HOSPEDAJE":0,
    #"Categoria de sitio_LOTE BALDIO":0,
    #"Categoria de sitio_OTRO":0,
    #"Categoria de sitio_SECTOR INDUSTRIA":0,
    #"Categoria de sitio_SECTOR MARITIMO Y FLUVIAL":0,
    #"Categoria de sitio_SERVICIO FUNERARIO":0,
    #"Categoria de sitio_VIAS PUBLICAS":0,
    #"Categoria de sitio_VIVIENDAS":0,
    #"Arma empleada_ARMA BLANCA / CORTOPUNZANTE":0,
    #"Arma empleada_ARMA DE FUEGO":0,
    #"Arma empleada_CONTUNDENTES":0,
    #"Arma empleada_ESCOPOLAMINA":0,
    #"Arma empleada_NO REPORTADO":0,
    #"Arma empleada_SIN EMPLEO DE ARMAS":0,
    #"Month_1":0,
    #"Month_2":0,
    #"Month_3":0,
    #"Month_4":0,
    #"Month_5":0,
    #"Month_6":0,
    #"Month_7":0,
    #"Month_8":0,
    #"Month_9":0,
    #"Month_10":0,
    #"Month_11":0,
    #"Month_12":0,
    "WeekDay_0":0,
    "WeekDay_1":0,
    "WeekDay_2":0,
    "WeekDay_3":0,
    "WeekDay_4":0,
    "WeekDay_5":0,
    "WeekDay_6":0,
    "Timeframe_Dia":0,
    "Timeframe_Madrugada":0,
    "Timeframe_Noche":0,
    #"Quincena":0,
    #"Dia_Madre":0,
    #"Carnaval":0
}

BARRIOS = ["Barrio_12 DE OCTUBRE",
"Barrio_20 DE JULIO",
"Barrio_7 DE ABRIL",
"Barrio_7 DE AGOSTO",
"Barrio_ALFONSO LOPEZ",
"Barrio_ALTAMIRA",
"Barrio_ALTO DE LOS ROBLES",
"Barrio_ALTO PRADO",
"Barrio_ALTOS DE RIOMAR",
"Barrio_ALTOS DEL LIMON",
"Barrio_AMERICA",
"Barrio_ANDALUCIA",
"Barrio_ATLANTICO",
"Barrio_BARLOVENTO",
"Barrio_BARRIO ABAJO",
"Barrio_BELLA ARENA",
"Barrio_BELLA MURILLO",
"Barrio_BELLAVISTA",
"Barrio_BETANIA",
"Barrio_BONANZA",
"Barrio_BOSTON",
"Barrio_BOYACA",
"Barrio_BUENA ESPERANZA",
"Barrio_BUENAVISTA",
"Barrio_BUENOS AIRES",
"Barrio_CABRERA",
"Barrio_CACHIMBERO",
"Barrio_CALIFORNIA",
"Barrio_CAMPO ALEGRE",
"Barrio_CARLOS MEISEL",
"Barrio_CARRIZAL",
"Barrio_CENTENARIO",
"Barrio_CENTRO",
"Barrio_CEVILLAR",
"Barrio_CHIQUINQUIRA",
"Barrio_CIUDAD BOLIVAR",
"Barrio_CIUDAD BONITA",
"Barrio_CIUDAD CAMELOT",
"Barrio_CIUDAD JARDIN",
"Barrio_CIUDAD MODESTO",
"Barrio_CIUDAD PARAISO",
"Barrio_CIUDADELA 20 DE JULIO",
"Barrio_CIUDADELA METROPOLITANA",
"Barrio_COLOMBIA",
"Barrio_CONJUNTO LOS MANGOS",
"Barrio_CONTINENTES",
"Barrio_CORDIALIDAD",
"Barrio_COSTA HERMOSA",
"Barrio_CUCHILLA DE VILLATE",
"Barrio_DELICIAS",
"Barrio_DOÑA MANUELA",
"Barrio_DOÑA SOLEDAD",
"Barrio_EL BOSQUE",
"Barrio_EL CAMPITO",
"Barrio_EL CARMEN",
"Barrio_EL CASTILLO",
"Barrio_EL EDEN 2000",
"Barrio_EL ENCANTO",
"Barrio_EL ESFUERZO",
"Barrio_EL FERROCARRIL",
"Barrio_EL FERRY",
"Barrio_EL GOLF",
"Barrio_EL GOLFO",
"Barrio_EL HIPODROMO",
"Barrio_EL LIMONCITO",
"Barrio_EL MANANTIAL",
"Barrio_EL MILAGRO",
"Barrio_EL OASIS",
"Barrio_EL PARQUE",
"Barrio_EL POBLADO",
"Barrio_EL PORVENIR",
"Barrio_EL PRADO",
"Barrio_EL PUEBLO",
"Barrio_EL RECREO",
"Barrio_EL ROMANCE",
"Barrio_EL ROSARIO",
"Barrio_EL SILENCIO",
"Barrio_EL TABOR",
"Barrio_EL TRIUNFO",
"Barrio_EL TUCAN",
"Barrio_EL VALLE",
"Barrio_EVARISTO SOURDIS",
"Barrio_GRANADILLO",
"Barrio_JERUSALEM",
"Barrio_JOSE ANTONIO GALAN",
"Barrio_JUAN DOMINGUEZ ROMERO",
"Barrio_JUAN MINA",
"Barrio_KALAMARY",
"Barrio_KENNEDY",
"Barrio_LA ALBORAYA",
"Barrio_LA ALIANZA",
"Barrio_LA ARBOLEDA",
"Barrio_LA CAMPIÑA",
"Barrio_LA CANDELARIA I",
"Barrio_LA CANDELARIA II",
"Barrio_LA CEIBA",
"Barrio_LA CENTRAL",
"Barrio_LA CHINITA",
"Barrio_LA CONCEPCION",
"Barrio_LA CRUZ DE MAYO",
"Barrio_LA CUMBRE",
"Barrio_LA ESMERALDA",
"Barrio_LA ESPERANZA",
"Barrio_LA FARRUCA",
"Barrio_LA FE",
"Barrio_LA FLORESTA",
"Barrio_LA FLORIDA",
"Barrio_LA GLORIA",
"Barrio_LA ILUSION",
"Barrio_LA INMACULADA",
"Barrio_LA LIBERTAD",
"Barrio_LA LOMA",
"Barrio_LA LUZ",
"Barrio_LA MAGDALENA",
"Barrio_LA MANGA",
"Barrio_LA MARIA",
"Barrio_LA PAZ",
"Barrio_LA PLAYA",
"Barrio_LA PRADERA",
"Barrio_LA SIERRA",
"Barrio_LA SIERRITA",
"Barrio_LA UNION",
"Barrio_LA VICTORIA",
"Barrio_LA VIOLA I",
"Barrio_LA VIOLA II",
"Barrio_LAS AMERICAS",
"Barrio_LAS COLINAS",
"Barrio_LAS COLONIAS",
"Barrio_LAS COMETAS",
"Barrio_LAS DUNAS",
"Barrio_LAS ESTRELLAS",
"Barrio_LAS FERIAS",
"Barrio_LAS FLORES",
"Barrio_LAS GARDENIAS",
"Barrio_LAS GAVIOTAS",
"Barrio_LAS GRANJAS",
"Barrio_LAS MALVINAS",
"Barrio_LAS MARGARITAS",
"Barrio_LAS MERCEDES",
"Barrio_LAS MORAS",
"Barrio_LAS NIEVES",
"Barrio_LAS NUBES",
"Barrio_LAS PALMAS",
"Barrio_LAS TERRAZAS",
"Barrio_LAS TORRES",
"Barrio_LAS TRES AVE MARIAS",
"Barrio_LAS TRINITARIAS",
"Barrio_LIMON",
"Barrio_LIPAYA",
"Barrio_LOMA FRESCA",
"Barrio_LOS ALMENDROS",
"Barrio_LOS ALMENDROS III",
"Barrio_LOS ALPES",
"Barrio_LOS ANDES",
"Barrio_LOS ANGELES I",
"Barrio_LOS ARRAYANES",
"Barrio_LOS BALCANES",
"Barrio_LOS CEDROS",
"Barrio_LOS CUSULES",
"Barrio_LOS FUNDADORES",
"Barrio_LOS GIRASOLES",
"Barrio_LOS JOBOS",
"Barrio_LOS LAURELES",
"Barrio_LOS LOTEROS",
"Barrio_LOS NOGALES",
"Barrio_LOS OLIVOS I",
"Barrio_LOS OLIVOS II",
"Barrio_LOS PINOS",
"Barrio_LOS ROBLES",
"Barrio_LOS ROSALES",
"Barrio_LOS TRUPILLOS",
"Barrio_LUCERO",
"Barrio_MANUELA BELTRAN",
"Barrio_ME QUEJO",
"Barrio_MERCEDES SUR",
"Barrio_MIRAMAR",
"Barrio_MODELO",
"Barrio_MONTECRISTO",
"Barrio_MONTES",
"Barrio_NORMANDIA",
"Barrio_NUEVA COLOMBIA",
"Barrio_NUEVA ESPERANZA I",
"Barrio_NUEVA GRANADA",
"Barrio_NUEVO HORIZONTE",
"Barrio_NUEVO MILENIO",
"Barrio_OLAYA HERRERA",
"Barrio_ORIENTAL",
"Barrio_PARAISO",
"Barrio_PASADENA",
"Barrio_PINAR DEL RIO",
"Barrio_POR FIN",
"Barrio_PORTAL DE LOS NOGALES",
"Barrio_PRADO SOLEDAD",
"Barrio_PRIMERO DE MAYO",
"Barrio_PUERTA DE ORO",
"Barrio_PUMAREJO",
"Barrio_REBOLO",
"Barrio_RENACER",
"Barrio_RESERVA DE LOS ALMENDROS",
"Barrio_RIOMAR",
"Barrio_SAL SI PUEDES",
"Barrio_SALAMANCA",
"Barrio_SALCEDO",
"Barrio_SAN ANTONIO",
"Barrio_SAN BERNARDO",
"Barrio_SAN FELIPE",
"Barrio_SAN FRANCISCO",
"Barrio_SAN ISIDRO",
"Barrio_SAN JOSE",
"Barrio_SAN LUIS",
"Barrio_SAN NICOLAS",
"Barrio_SAN PEDRO ALEJANDRINO",
"Barrio_SAN ROQUE",
"Barrio_SAN SALVADOR",
"Barrio_SAN VICENTE",
"Barrio_SANTA ANA",
"Barrio_SANTA HELENA",
"Barrio_SANTA INES",
"Barrio_SANTA MARIA",
"Barrio_SANTA MONICA",
"Barrio_SANTO DOMINGO",
"Barrio_SANTO DOMINGO DE GUZMAN",
"Barrio_SANTUARIO",
"Barrio_SIAPE",
"Barrio_SIMON BOLIVAR",
"Barrio_SOLEDAD 2000",
"Barrio_TAYRONA",
"Barrio_TERRANOVA II",
"Barrio_UNIVERSAL",
"Barrio_VILLA ADELA",
"Barrio_VILLA BLANCA",
"Barrio_VILLA CAMPESTRE",
"Barrio_VILLA CAROLINA",
"Barrio_VILLA CECILIA",
"Barrio_VILLA COUNTRY",
"Barrio_VILLA DEL CARMEN",
"Barrio_VILLA DEL ESTE",
"Barrio_VILLA DEL REY",
"Barrio_VILLA DEL ROSARIO",
"Barrio_VILLA ESTADIO I",
"Barrio_VILLA ESTADIO II",
"Barrio_VILLA ESTADIO III",
"Barrio_VILLA ESTEFANNY",
"Barrio_VILLA FLOR",
"Barrio_VILLA KARLA",
"Barrio_VILLA KATANGA",
"Barrio_VILLA LAS MORAS I",
"Barrio_VILLA LAS MORAS II",
"Barrio_VILLA LINDA",
"Barrio_VILLA LOZANO",
"Barrio_VILLA MARIA",
"Barrio_VILLA MERLY",
"Barrio_VILLA MONACO",
"Barrio_VILLA MONIK",
"Barrio_VILLA MUVDI",
"Barrio_VILLA ROSA",
"Barrio_VILLA SAN CARLOS",
"Barrio_VILLA SAN PEDRO II",
"Barrio_VILLA SANTOS",
"Barrio_VILLA SELENE",
"Barrio_VILLA SEVERA",
"Barrio_VILLA SEVILLA",
"Barrio_VILLA SOL",
"Barrio_VILLA SOLEDAD",
"Barrio_VILLA VALENTINA",
"Barrio_VILLA ZAMBRANO",
"Barrio_VILLANUEVA",
"Barrio_VILLAS DE SAN PABLO",
"Barrio_VILLAS DEL PORTAL",
"Barrio_VILLATE",
"Barrio_VISTA HERMOSA",
"Barrio_ZONA FRANCA",
]
